import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import MessagePrivate from '@/components/MessagePrivate'
import SpeakFreely from '@/components/SpeakFreely'
import BottomHalf from '@/components/BottomHalf'
import ConnectWithUs from '@/components/ConnectWithUs'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
         <Navbar/>
      </header>
      <main className='bg-yellow-300 pt-[9rem] text-black z-10'>
         <MessagePrivate/>
         <SpeakFreely/>
         <BottomHalf/>
         <ConnectWithUs/>
      </main>
      <footer>
         <Footer/>
      </footer>  
    </>
  )
}
